### ISSUE TITLE
Tapping "Payment" right after opening the app and before the "Touch ID" message appears crashes the app

### ISSUE THREAD

**Issue by 44MordFustang** [JediWed/Mana#11]
Opening Mana and immediately tapping on "Payment", before the "Touch ID" message pops up, crashes the app.
Issue is reproduceable with version 1.0.0 (2) on iPhone 8,1 and iOS 10.1.1 (14B100).

**Comment by JediWed** [comment]
Fixed by disabling all tabs on app start and enabling after authenticating (or if no authentication was set up)
